version: "2"

services:

  django:
    build:
      context: ./django
      args:
        - "https_proxy=${https_proxy}"
    #image: kokardy/django
    #restart: always
    command: ["./entrypoint.sh"]
    #command: ["tail", "-f", "/dev/null"]
    environment:
      - "PROJECT_NAME=project2"
    env_file:
      - common_env
    depends_on:
      - postgres
    volumes_from:
      - storage
    volumes:
      - ./asset:/asset

  postgres:
    image: postgres:9.5-alpine
    #restart: always
    env_file:
      - common_env
    volumes_from:
      - storage

  nginx:
    image: nginx:alpine
    #restart: always
    ports:
      - "10000:80"
    volumes_from:
      - storage
    links:
      - django

  storage:
    image: alpine
    volumes:
      - ./nginx/static:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./pg/initdb:/docker-entrypoint-initdb.d

      #PostgreSQLのデータ永続化
      #- ./pg/pgdata:/var/lib/postgresql/data

