# Generated by Django 3.1.7 on 2021-02-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_book_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('age', models.IntegerField(db_index=True)),
                ('books', models.ManyToManyField(to='app1.Book')),
            ],
        ),
    ]
