"""
This type stub file was generated by pyright.
"""

TIME_STRINGS = ...
TIMESINCE_CHUNKS = ...
def timesince(d, now=..., reversed=..., time_strings=..., depth=...):
    """
    Take two datetime objects and return the time between d and now as a nicely
    formatted string, e.g. "10 minutes". If d occurs after now, return
    "0 minutes".

    Units used are years, months, weeks, days, hours, and minutes.
    Seconds and microseconds are ignored. Up to `depth` adjacent units will be
    displayed.  For example, "2 weeks, 3 days" and "1 year, 3 months" are
    possible outputs, but "2 weeks, 3 hours" and "1 year, 5 days" are not.

    `time_strings` is an optional dict of strings to replace the default
    TIME_STRINGS dict.

    `depth` is an optional integer to control the number of adjacent time
    units returned.

    Adapted from
    https://web.archive.org/web/20060617175230/http://blog.natbat.co.uk/archive/2003/Jun/14/time_since
    """
    ...

def timeuntil(d, now=..., time_strings=..., depth=...): # -> Any:
    """
    Like timesince, but return a string measuring the time until the given time.
    """
    ...

