"""
This type stub file was generated by pyright.
"""

from django.db.models.lookups import Exact, GreaterThan, GreaterThanOrEqual, In, IsNull, LessThan, LessThanOrEqual

class MultiColSource:
    contains_aggregate = ...
    def __init__(self, alias, targets, sources, field) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def relabeled_clone(self, relabels): # -> Self@MultiColSource:
        ...
    
    def get_lookup(self, lookup):
        ...
    
    def resolve_expression(self, *args, **kwargs): # -> Self@MultiColSource:
        ...
    


def get_normalized_value(value, lhs):
    ...

class RelatedIn(In):
    def get_prep_lookup(self): # -> list[Unknown]:
        ...
    
    def as_sql(self, compiler, connection):
        ...
    


class RelatedLookupMixin:
    def get_prep_lookup(self):
        ...
    
    def as_sql(self, compiler, connection):
        ...
    


class RelatedExact(RelatedLookupMixin, Exact):
    ...


class RelatedLessThan(RelatedLookupMixin, LessThan):
    ...


class RelatedGreaterThan(RelatedLookupMixin, GreaterThan):
    ...


class RelatedGreaterThanOrEqual(RelatedLookupMixin, GreaterThanOrEqual):
    ...


class RelatedLessThanOrEqual(RelatedLookupMixin, LessThanOrEqual):
    ...


class RelatedIsNull(RelatedLookupMixin, IsNull):
    ...


