"""
This type stub file was generated by pyright.
"""

from enum import Enum

__all__ = ['CheckConstraint', 'Deferrable', 'UniqueConstraint']
class BaseConstraint:
    def __init__(self, name) -> None:
        ...
    
    @property
    def contains_expressions(self): # -> Literal[False]:
        ...
    
    def constraint_sql(self, model, schema_editor):
        ...
    
    def create_sql(self, model, schema_editor):
        ...
    
    def remove_sql(self, model, schema_editor):
        ...
    
    def deconstruct(self): # -> tuple[str, tuple[()], dict[str, Unknown]]:
        ...
    
    def clone(self): # -> Self@BaseConstraint:
        ...
    


class CheckConstraint(BaseConstraint):
    def __init__(self, *, check, name) -> None:
        ...
    
    def constraint_sql(self, model, schema_editor):
        ...
    
    def create_sql(self, model, schema_editor):
        ...
    
    def remove_sql(self, model, schema_editor):
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def deconstruct(self): # -> tuple[str, tuple[()], dict[str, Unknown]]:
        ...
    


class Deferrable(Enum):
    DEFERRED = ...
    IMMEDIATE = ...
    def __repr__(self): # -> str:
        ...
    


class UniqueConstraint(BaseConstraint):
    def __init__(self, *expressions, fields=..., name=..., condition=..., deferrable=..., include=..., opclasses=...) -> None:
        ...
    
    @property
    def contains_expressions(self): # -> bool:
        ...
    
    def constraint_sql(self, model, schema_editor):
        ...
    
    def create_sql(self, model, schema_editor):
        ...
    
    def remove_sql(self, model, schema_editor):
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def deconstruct(self): # -> tuple[str, tuple[F | Unknown, ...], dict[str, Unknown]]:
        ...
    


