"""
This type stub file was generated by pyright.
"""

from . import Tags, register

E001 = ...
E002 = ...
@register(Tags.templates)
def check_setting_app_dirs_loaders(app_configs, **kwargs): # -> list[Error]:
    ...

@register(Tags.templates)
def check_string_if_invalid_is_string(app_configs, **kwargs): # -> list[Unknown]:
    ...

