# Generated by Django 3.1.7 on 2021-02-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, default='no_title', max_length=255),
            preserve_default=False,
        ),
    ]
